project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "MUSA 550 Quarto Page - Ann Zhang"
  site-url: "https://annannzhang.github.io/Python-Projects" 
  repo-url: https://github.com/annannzhang/Python-Projects
  repo-actions: [source]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-Ann Zhang, 2023"

  sidebar:
    foreground: dark
    background: white
    border: false
    logo: "images/AZ_Logo.png"
    pinned: false
    align: center
    tools: 
      - icon: globe
        href: https://annannzhang.github.io
        text: "Personal Website"
       

    style: "docked"
    
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - about.qmd
      - section: analysis/index.qmd
        contents:
          - analysis/assignment-1.ipynb
          - analysis/assignment-2.ipynb
          - analysis/assignment-4.ipynb
          - analysis/assignment-5.ipynb
          - analysis/assignment-6.ipynb
          

format:
  html:
    highlight-style: solarized
    theme: Cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true




